export const countries = [
  { id: 2589581, name: "Algeria", level: "country" },
  { id: 3041565, name: "Andorra", level: "country" },
  { id: 3351879, name: "Angola", level: "country" },
  { id: 3576396, name: "Antigua and Barbuda", level: "country" },
  { id: 3865483, name: "Argentina", level: "country" },
  { id: null, name: "Armenia", level: "country" },
  { id: 2077456, name: "Australia", level: "country" },
  { id: 2782113, name: "Austria", level: "country" },
  { id: 587116, name: "Azerbaijan", level: "country" },
  { id: 3572887, name: "Bahamas", level: "country" },
  { id: 290291, name: "Bahrain", level: "country" },
  { id: 1210997, name: "Bangladesh", level: "country" },
  { id: 3374084, name: "Barbados", level: "country" },
  { id: 630336, name: "Belarus", level: "country" },
  { id: 2802361, name: "Belgium", level: "country" },
  { id: 3582678, name: "Belize", level: "country" },
  { id: null, name: "Benin", level: "country" },
  { id: null, name: "Bhutan", level: "country" },
  { id: 3923057, name: "Bolivia", level: "country" },
  { id: 3277605, name: "Bosnia and Herzegovina", level: "country" },
  { id: null, name: "Botswana", level: "country" },
  { id: 3469034, name: "Brazil", level: "country" },
  { id: null, name: "Brunei", level: "country" },
  { id: 732800, name: "Bulgaria", level: "country" },
  { id: null, name: "Burkina Faso", level: "country" },
  { id: null, name: "Burundi", level: "country" },
  { id: 1831722, name: "Cambodia", level: "country" },
  { id: null, name: "Cameroon", level: "country" },
  { id: 6251999, name: "Canada", level: "country" },
  { id: 3374766, name: "Cape Verde", level: "country" },
  { id: null, name: "Central African Republic", level: "country" },
  { id: null, name: "Chad", level: "country" },
  { id: 3895114, name: "Chile", level: "country" },
  { id: null, name: "China", level: "country" },
  { id: 3686110, name: "Colombia", level: "country" },
  { id: 921929, name: "Comoros", level: "country" },
  { id: null, name: "Congo", level: "country" },
  { id: 203312, name: "Congo (Democratic Republic)", level: "country" },
  { id: 3624060, name: "Costa Rica", level: "country" },
  { id: 3202326, name: "Croatia", level: "country" },
  { id: 3562981, name: "Cuba", level: "country" },
  { id: null, name: "Cyprus", level: "country" },
  { id: 3077311, name: "Czech Republic", level: "country" },
  { id: 2623032, name: "Denmark", level: "country" },
  { id: 223816, name: "Djibouti", level: "country" },
  { id: 3575830, name: "Dominica", level: "country" },
  { id: 3508796, name: "Dominican Republic", level: "country" },
  { id: 3658394, name: "Ecuador", level: "country" },
  { id: 357994, name: "Egypt", level: "country" },
  { id: 3585968, name: "El Salvador", level: "country" },
  { id: 2309096, name: "Equatorial Guinea", level: "country" },
  { id: 338010, name: "Eritrea", level: "country" },
  { id: 453733, name: "Estonia", level: "country" },
  { id: null, name: "Eswatini", level: "country" },
  { id: null, name: "Ethiopia", level: "country" },
  { id: null, name: "Fiji", level: "country" },
  { id: 660013, name: "Finland", level: "country" },
  { id: 3017382, name: "France", level: "country" },
  { id: null, name: "Gabon", level: "country" },
  { id: null, name: "Gambia", level: "country" },
  { id: 614540, name: "Georgia", level: "country" },
  { id: 2921044, name: "Germany", level: "country" },
  { id: null, name: "Ghana", level: "country" },
  { id: 390903, name: "Greece", level: "country" },
  { id: 3580239, name: "Grenada", level: "country" },
  { id: 3595528, name: "Guatemala", level: "country" },
  { id: 2420477, name: "Guinea", level: "country" },
  { id: 2372248, name: "Guinea-Bissau", level: "country" },
  { id: null, name: "Guyana", level: "country" },
  { id: 3723988, name: "Haiti", level: "country" },
  { id: 3608932, name: "Honduras", level: "country" },
  { id: 719819, name: "Hungary", level: "country" },
  { id: 2629691, name: "Iceland", level: "country" },
  { id: 1269750, name: "India", level: "country" },
  { id: 1643084, name: "Indonesia", level: "country" },
  { id: null, name: "Iran", level: "country" },
  { id: 99237, name: "Iraq", level: "country" },
  { id: 2963597, name: "Ireland", level: "country" },
  { id: 294640, name: "Israel", level: "country" },
  { id: 3175395, name: "Italy", level: "country" },
  { id: 3489940, name: "Jamaica", level: "country" },
  { id: 1861060, name: "Japan", level: "country" },
  { id: 248816, name: "Jordan", level: "country" },
  { id: 1522867, name: "Kazakhstan", level: "country" },
  { id: 192950, name: "Kenya", level: "country" },
  { id: null, name: "Kiribati", level: "country" },
  { id: 1835841, name: "Korea, South", level: "country" },
  { id: 285570, name: "Kuwait", level: "country" },
  { id: null, name: "Kyrgyzstan", level: "country" },
  { id: null, name: "Laos", level: "country" },
  { id: 458258, name: "Latvia", level: "country" },
  { id: 272103, name: "Lebanon", level: "country" },
  { id: null, name: "Lesotho", level: "country" },
  { id: null, name: "Liberia", level: "country" },
  { id: 2215636, name: "Libya", level: "country" },
  { id: 3042058, name: "Liechtenstein", level: "country" },
  { id: 597427, name: "Lithuania", level: "country" },
  { id: 2960313, name: "Luxembourg", level: "country" },
  { id: null, name: "Madagascar", level: "country" },
  { id: null, name: "Malawi", level: "country" },
  { id: 1733045, name: "Malaysia", level: "country" },
  { id: null, name: "Maldives", level: "country" },
  { id: null, name: "Mali", level: "country" },
  { id: 2562770, name: "Malta", level: "country" },
  { id: null, name: "Marshall Islands", level: "country" },
  { id: 2378080, name: "Mauritania", level: "country" },
  { id: null, name: "Mauritius", level: "country" },
  { id: 3996063, name: "Mexico", level: "country" },
  { id: null, name: "Micronesia", level: "country" },
  { id: 617790, name: "Moldova", level: "country" },
  { id: 2993457, name: "Monaco", level: "country" },
  { id: null, name: "Mongolia", level: "country" },
  { id: 3194884, name: "Montenegro", level: "country" },
  { id: 2542007, name: "Morocco", level: "country" },
  { id: 1036973, name: "Mozambique", level: "country" },
  { id: 1327865, name: "Myanmar", level: "country" },
  { id: null, name: "Namibia", level: "country" },
  { id: null, name: "Nauru", level: "country" },
  { id: null, name: "Nepal", level: "country" },
  { id: 2750405, name: "Netherlands", level: "country" },
  { id: 2186224, name: "New Zealand", level: "country" },
  { id: 3617476, name: "Nicaragua", level: "country" },
  { id: null, name: "Niger", level: "country" },
  { id: 2328926, name: "Nigeria", level: "country" },
  { id: 718075, name: "North Macedonia", level: "country" },
  { id: 3144096, name: "Norway", level: "country" },
  { id: 286963, name: "Oman", level: "country" },
  { id: 1168579, name: "Pakistan", level: "country" },
  { id: null, name: "Palau", level: "country" },
  { id: 3703430, name: "Panama", level: "country" },
  { id: null, name: "Papua New Guinea", level: "country" },
  { id: 3437598, name: "Paraguay", level: "country" },
  { id: 3932488, name: "Peru", level: "country" },
  { id: 1694008, name: "Philippines", level: "country" },
  { id: 798544, name: "Poland", level: "country" },
  { id: 2264397, name: "Portugal", level: "country" },
  { id: 289688, name: "Qatar", level: "country" },
  { id: 798549, name: "Romania", level: "country" },
  { id: 2017370, name: "Russia", level: "country" },
  { id: null, name: "Rwanda", level: "country" },
  { id: 3575174, name: "Saint Kitts and Nevis", level: "country" },
  { id: 3576468, name: "Saint Lucia", level: "country" },
  { id: 3577815, name: "Saint Vincent and the Grenadines", level: "country" },
  { id: null, name: "Samoa", level: "country" },
  { id: 3168068, name: "San Marino", level: "country" },
  { id: 2410758, name: "Sao Tome and Principe", level: "country" },
  { id: 102358, name: "Saudi Arabia", level: "country" },
  { id: null, name: "Senegal", level: "country" },
  { id: 6290252, name: "Serbia", level: "country" },
  { id: null, name: "Seychelles", level: "country" },
  { id: null, name: "Sierra Leone", level: "country" },
  { id: 1880251, name: "Singapore", level: "country" },
  { id: 3057568, name: "Slovakia", level: "country" },
  { id: 3190538, name: "Slovenia", level: "country" },
  { id: null, name: "Solomon Islands", level: "country" },
  { id: 51537, name: "Somalia", level: "country" },
  { id: 953987, name: "South Africa", level: "country" },
  { id: 7909807, name: "South Sudan", level: "country" },
  { id: 2510769, name: "Spain", level: "country" },
  { id: 1227603, name: "Sri Lanka", level: "country" },
  { id: 366755, name: "Sudan", level: "country" },
  { id: null, name: "Suriname", level: "country" },
  { id: 2661886, name: "Sweden", level: "country" },
  { id: 2658434, name: "Switzerland", level: "country" },
  { id: 163843, name: "Syria", level: "country" },
  { id: 1668284, name: "Taiwan", level: "country/region" },
  { id: null, name: "Tajikistan", level: "country" },
  { id: null, name: "Tanzania", level: "country" },
  { id: 1605651, name: "Thailand", level: "country" },
  { id: null, name: "Timor-Leste", level: "country" },
  { id: null, name: "Togo", level: "country" },
  { id: null, name: "Tonga", level: "country" },
  { id: 3573591, name: "Trinidad and Tobago", level: "country" },
  { id: 2464461, name: "Tunisia", level: "country" },
  { id: 298795, name: "Turkey", level: "country" },
  { id: null, name: "Turkmenistan", level: "country" },
  { id: null, name: "Tuvalu", level: "country" },
  { id: null, name: "Uganda", level: "country" },
  { id: 690791, name: "Ukraine", level: "country" },
  { id: 290557, name: "United Arab Emirates", level: "country" },
  { id: 2635167, name: "United Kingdom", level: "country" },
  { id: 6252001, name: "United States", level: "country" },
  { id: 3439705, name: "Uruguay", level: "country" },
  { id: 1512440, name: "Uzbekistan", level: "country" },
  { id: null, name: "Vanuatu", level: "country" },
  { id: 3041563, name: "Vatican City", level: "country" },
  { id: 3625428, name: "Venezuela", level: "country" },
  { id: 1562822, name: "Vietnam", level: "country" },
  { id: 69543, name: "Yemen", level: "country" },
  { id: null, name: "Zambia", level: "country" },
  { id: null, name: "Zimbabwe", level: "country" }
];