export const countries = [
  { id: 2589581, name: "Algeria", level: "country", code: "DZ" },
  { id: 3041565, name: "Andorra", level: "country", code: "AD" },
  { id: 3351879, name: "Angola", level: "country", code: "AO" },
  { id: 3576396, name: "Antigua and Barbuda", level: "country", code: "AG" },
  { id: 3865483, name: "Argentina", level: "country", code: "AR" },
  { id: null, name: "Armenia", level: "country", code: "AM" },
  { id: 2077456, name: "Australia", level: "country", code: "AU" },
  { id: 2782113, name: "Austria", level: "country", code: "AT" },
  { id: 587116, name: "Azerbaijan", level: "country", code: "AZ" },
  { id: 3572887, name: "Bahamas", level: "country", code: "BS" },
  { id: 290291, name: "Bahrain", level: "country", code: "BH" },
  { id: 1210997, name: "Bangladesh", level: "country", code: "BD" },
  { id: 3374084, name: "Barbados", level: "country", code: "BB" },
  { id: 630336, name: "Belarus", level: "country", code: "BY" },
  { id: 2802361, name: "Belgium", level: "country", code: "BE" },
  { id: 3582678, name: "Belize", level: "country", code: "BZ" },
  { id: null, name: "Benin", level: "country", code: "BJ" },
  { id: null, name: "Bhutan", level: "country", code: "BT" },
  { id: 3923057, name: "Bolivia", level: "country", code: "BO" },
  { id: 3277605, name: "Bosnia and Herzegovina", level: "country", code: "BA" },
  { id: null, name: "Botswana", level: "country", code: "BW" },
  { id: 3469034, name: "Brazil", level: "country", code: "BR" },
  { id: null, name: "Brunei", level: "country", code: "BN" },
  { id: 732800, name: "Bulgaria", level: "country", code: "BG" },
  { id: null, name: "Burkina Faso", level: "country", code: "BF" },
  { id: null, name: "Burundi", level: "country", code: "BI" },
  { id: 1831722, name: "Cambodia", level: "country", code: "KH" },
  { id: null, name: "Cameroon", level: "country", code: "CM" },
  { id: 6251999, name: "Canada", level: "country", code: "CA" },
  { id: 3374766, name: "Cape Verde", level: "country", code: "CV" },
  { id: null, name: "Central African Republic", level: "country", code: "CF" },
  { id: null, name: "Chad", level: "country", code: "TD" },
  { id: 3895114, name: "Chile", level: "country", code: "CL" },
  { id: null, name: "China", level: "country", code: "CN" },
  { id: 3686110, name: "Colombia", level: "country", code: "CO" },
  { id: 921929, name: "Comoros", level: "country", code: "KM" },
  { id: null, name: "Congo", level: "country", code: "CG" },
  { id: 203312, name: "Congo (Democratic Republic)", level: "country", code: "CD" },
  { id: 3624060, name: "Costa Rica", level: "country", code: "CR" },
  { id: 3202326, name: "Croatia", level: "country", code: "HR" },
  { id: 3562981, name: "Cuba", level: "country", code: "CU" },
  { id: null, name: "Cyprus", level: "country", code: "CY" },
  { id: 3077311, name: "Czech Republic", level: "country", code: "CZ" },
  { id: 2623032, name: "Denmark", level: "country", code: "DK" },
  { id: 223816, name: "Djibouti", level: "country", code: "DJ" },
  { id: 3575830, name: "Dominica", level: "country", code: "DM" },
  { id: 3508796, name: "Dominican Republic", level: "country", code: "DO" },
  { id: 3658394, name: "Ecuador", level: "country", code: "EC" },
  { id: 357994, name: "Egypt", level: "country", code: "EG" },
  { id: 3585968, name: "El Salvador", level: "country", code: "SV" },
  { id: 2309096, name: "Equatorial Guinea", level: "country", code: "GQ" },
  { id: 338010, name: "Eritrea", level: "country", code: "ER" },
  { id: 453733, name: "Estonia", level: "country", code: "EE" },
  { id: null, name: "Eswatini", level: "country", code: "SZ" },
  { id: null, name: "Ethiopia", level: "country", code: "ET" },
  { id: null, name: "Fiji", level: "country", code: "FJ" },
  { id: 660013, name: "Finland", level: "country", code: "FI" },
  { id: 3017382, name: "France", level: "country", code: "FR" },
  { id: null, name: "Gabon", level: "country", code: "GA" },
  { id: null, name: "Gambia", level: "country", code: "GM" },
  { id: 614540, name: "Georgia", level: "country", code: "GE" },
  { id: 2921044, name: "Germany", level: "country", code: "DE" },
  { id: null, name: "Ghana", level: "country", code: "GH" },
  { id: 390903, name: "Greece", level: "country", code: "GR" },
  { id: 3580239, name: "Grenada", level: "country", code: "GD" },
  { id: 3595528, name: "Guatemala", level: "country", code: "GT" },
  { id: 2420477, name: "Guinea", level: "country", code: "GN" },
  { id: 2372248, name: "Guinea-Bissau", level: "country", code: "GW" },
  { id: null, name: "Guyana", level: "country", code: "GY" },
  { id: 3723988, name: "Haiti", level: "country", code: "HT" },
  { id: 3608932, name: "Honduras", level: "country", code: "HN" },
  { id: 719819, name: "Hungary", level: "country", code: "HU" },
  { id: 2629691, name: "Iceland", level: "country", code: "IS" },
  { id: 1269750, name: "India", level: "country", code: "IN" },
  { id: 1643084, name: "Indonesia", level: "country", code: "ID" },
  { id: null, name: "Iran", level: "country", code: "IR" },
  { id: 99237, name: "Iraq", level: "country", code: "IQ" },
  { id: 2963597, name: "Ireland", level: "country", code: "IE" },
  { id: 294640, name: "Israel", level: "country", code: "IL" },
  { id: 3175395, name: "Italy", level: "country", code: "IT" },
  { id: 3489940, name: "Jamaica", level: "country", code: "JM" },
  { id: 1861060, name: "Japan", level: "country", code: "JP" },
  { id: 248816, name: "Jordan", level: "country", code: "JO" },
  { id: 1522867, name: "Kazakhstan", level: "country", code: "KZ" },
  { id: 192950, name: "Kenya", level: "country", code: "KE" },
  { id: null, name: "Kiribati", level: "country", code: "KI" },
  { id: 1835841, name: "Korea, South", level: "country", code: "KR" },
  { id: 285570, name: "Kuwait", level: "country", code: "KW" },
  { id: null, name: "Kyrgyzstan", level: "country", code: "KG" },
  { id: null, name: "Laos", level: "country", code: "LA" },
  { id: 458258, name: "Latvia", level: "country", code: "LV" },
  { id: 272103, name: "Lebanon", level: "country", code: "LB" },
  { id: null, name: "Lesotho", level: "country", code: "LS" },
  { id: null, name: "Liberia", level: "country", code: "LR" },
  { id: 2215636, name: "Libya", level: "country", code: "LY" },
  { id: 3042058, name: "Liechtenstein", level: "country", code: "LI" },
  { id: 597427, name: "Lithuania", level: "country", code: "LT" },
  { id: 2960313, name: "Luxembourg", level: "country", code: "LU" },
  { id: null, name: "Madagascar", level: "country", code: "MG" },
  { id: null, name: "Malawi", level: "country", code: "MW" },
  { id: 1733045, name: "Malaysia", level: "country", code: "MY" },
  { id: null, name: "Maldives", level: "country", code: "MV" },
  { id: null, name: "Mali", level: "country", code: "ML" },
  { id: 2562770, name: "Malta", level: "country", code: "MT" },
  { id: null, name: "Marshall Islands", level: "country", code: "MH" },
  { id: 2378080, name: "Mauritania", level: "country", code: "MR" },
  { id: null, name: "Mauritius", level: "country", code: "MU" },
  { id: 3996063, name: "Mexico", level: "country", code: "MX" },
  { id: null, name: "Micronesia", level: "country", code: "FM" },
  { id: 617790, name: "Moldova", level: "country", code: "MD" },
  { id: 2993457, name: "Monaco", level: "country", code: "MC" },
  { id: null, name: "Mongolia", level: "country", code: "MN" },
  { id: 3194884, name: "Montenegro", level: "country", code: "ME" },
  { id: 2542007, name: "Morocco", level: "country", code: "MA" },
  { id: 1036973, name: "Mozambique", level: "country", code: "MZ" },
  { id: 1327865, name: "Myanmar", level: "country", code: "MM" },
  { id: null, name: "Namibia", level: "country", code: "NA" },
  { id: null, name: "Nauru", level: "country", code: "NR" },
  { id: null, name: "Nepal", level: "country", code: "NP" },
  { id: 2750405, name: "Netherlands", level: "country", code: "NL" },
  { id: 2186224, name: "New Zealand", level: "country", code: "NZ" },
  { id: 3617476, name: "Nicaragua", level: "country", code: "NI" },
  { id: null, name: "Niger", level: "country", code: "NE" },
  { id: 2328926, name: "Nigeria", level: "country", code: "NG" },
  { id: 718075, name: "North Macedonia", level: "country", code: "MK" },
  { id: 3144096, name: "Norway", level: "country", code: "NO" },
  { id: 286963, name: "Oman", level: "country", code: "OM" },
  { id: 1168579, name: "Pakistan", level: "country", code: "PK" },
  { id: null, name: "Palau", level: "country", code: "PW" },
  { id: 3703430, name: "Panama", level: "country", code: "PA" },
  { id: null, name: "Papua New Guinea", level: "country", code: "PG" },
  { id: 3437598, name: "Paraguay", level: "country", code: "PY" },
  { id: 3932488, name: "Peru", level: "country", code: "PE" },
  { id: 1694008, name: "Philippines", level: "country", code: "PH" },
  { id: 798544, name: "Poland", level: "country", code: "PL" },
  { id: 2264397, name: "Portugal", level: "country", code: "PT" },
  { id: 289688, name: "Qatar", level: "country", code: "QA" },
  { id: 798549, name: "Romania", level: "country", code: "RO" },
  { id: 2017370, name: "Russia", level: "country", code: "RU" },
  { id: null, name: "Rwanda", level: "country", code: "RW" },
  { id: 3575174, name: "Saint Kitts and Nevis", level: "country", code: "KN" },
  { id: 3576468, name: "Saint Lucia", level: "country", code: "LC" },
  { id: 3577815, name: "Saint Vincent and the Grenadines", level: "country", code: "VC" },
  { id: null, name: "Samoa", level: "country", code: "WS" },
  { id: 3168068, name: "San Marino", level: "country", code: "SM" },
  { id: 2410758, name: "Sao Tome and Principe", level: "country", code: "ST" },
  { id: 102358, name: "Saudi Arabia", level: "country", code: "SA" },
  { id: null, name: "Senegal", level: "country", code: "SN" },
  { id: 6290252, name: "Serbia", level: "country", code: "RS" },
  { id: null, name: "Seychelles", level: "country", code: "SC" },
  { id: null, name: "Sierra Leone", level: "country", code: "SL" },
  { id: 1880251, name: "Singapore", level: "country", code: "SG" },
  { id: 3057568, name: "Slovakia", level: "country", code: "SK" },
  { id: 3190538, name: "Slovenia", level: "country", code: "SI" },
  { id: null, name: "Solomon Islands", level: "country", code: "SB" },
  { id: 51537, name: "Somalia", level: "country", code: "SO" },
  { id: 953987, name: "South Africa", level: "country", code: "ZA" },
  { id: 7909807, name: "South Sudan", level: "country", code: "SS" },
  { id: 2510769, name: "Spain", level: "country", code: "ES" },
  { id: 1227603, name: "Sri Lanka", level: "country", code: "LK" },
  { id: 366755, name: "Sudan", level: "country", code: "SD" },
  { id: null, name: "Suriname", level: "country", code: "SR" },
  { id: 2661886, name: "Sweden", level: "country", code: "SE" },
  { id: 2658434, name: "Switzerland", level: "country", code: "CH" },
  { id: 163843, name: "Syria", level: "country", code: "SY" },
  { id: 1668284, name: "Taiwan", level: "country/region", code: "TW" },
  { id: null, name: "Tajikistan", level: "country", code: "TJ" },
  { id: null, name: "Tanzania", level: "country", code: "TZ" },
  { id: 1605651, name: "Thailand", level: "country", code: "TH" },
  { id: null, name: "Timor-Leste", level: "country", code: "TL" },
  { id: null, name: "Togo", level: "country", code: "TG" },
  { id: null, name: "Tonga", level: "country", code: "TO" },
  { id: 3573591, name: "Trinidad and Tobago", level: "country", code: "TT" },
  { id: 2464461, name: "Tunisia", level: "country", code: "TN" },
  { id: 298795, name: "Turkey", level: "country", code: "TR" },
  { id: null, name: "Turkmenistan", level: "country", code: "TM" },
  { id: null, name: "Tuvalu", level: "country", code: "TV" },
  { id: null, name: "Uganda", level: "country", code: "UG" },
  { id: 690791, name: "Ukraine", level: "country", code: "UA" },
  { id: 290557, name: "United Arab Emirates", level: "country", code: "AE" },
  { id: 2635167, name: "United Kingdom", level: "country", code: "GB" },
  { id: 6252001, name: "United States", level: "country", code: "US" },
  { id: 3439705, name: "Uruguay", level: "country", code: "UY" },
  { id: 1512440, name: "Uzbekistan", level: "country", code: "UZ" },
  { id: null, name: "Vanuatu", level: "country", code: "VU" },
  { id: 3041563, name: "Vatican City", level: "country", code: "VA" },
  { id: 3625428, name: "Venezuela", level: "country", code: "VE" },
  { id: 1562822, name: "Vietnam", level: "country", code: "VN" },
  { id: 69543, name: "Yemen", level: "country", code: "YE" },
  { id: null, name: "Zambia", level: "country", code: "ZM" },
  { id: null, name: "Zimbabwe", level: "country", code: "ZW" }
];